### ISSUE TITLE
The service is not published after the start

### ISSUE THREAD

**Issue by v4grishy** [avahi/avahi#601]
**Version:** `0.7`  
**Arch:** `arm64`  

This happens with some probability. After launching avahi-daemon, only a part of the services starts working and is displayed in avahi-browse, although all services are shown in the logs of avahi itself as established.

You can see below that avahi started 2 services.
-  `/services/qm-device.service` successfully established.
- `/services/qm-sw.service` successfully established.

But avahi's output and traffic does not contain `qm-sw.service`. And restart of avahi helped.

## Avahi logs

```plain
-- Logs begin at Tue 2024-04-30 10:07:37 UTC, end at Mon 2024-05-06 08:01:52 UTC. --
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Found user 'avahi' (UID 108) and group 'avahi' (GID 113).
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Successfully dropped root privileges.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: avahi-daemon 0.7 starting up.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[593]: chroot.c: chroot() helper started
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Successfully called chroot().
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Successfully dropped remaining capabilities.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[593]: chroot.c: chroot() helper got command 02
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Loading service file /services/qm-device.service.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Loading service file /services/qm-sw.service.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Network interface enumeration completed.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Registering new address record for fe80::d263:b4ff:fe03:4ec7 on eth0.*.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Server startup complete. Host name is qm-d063b4034ec7.local. Local service cookie is 3876857608.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Service "$svc$['Aliens', 'gateways']$" (/services/qm-sw.service) successfully established.
May 06 07:53:46 qm-d063b4034ec7 avahi-daemon[591]: Service "... on qm-d063b4034ec7" (/services/qm-device.service) successfully established.
May 06 07:53:50 qm-d063b4034ec7 avahi-daemon[591]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.88.252.
May 06 07:53:50 qm-d063b4034ec7 avahi-daemon[591]: New relevant interface eth0.IPv4 for mDNS.
May 06 07:53:50 qm-d063b4034ec7 avahi-daemon[591]: Registering new address record for 192.168.88.252 on eth0.IPv4.
```

### `avahi-browse -arkpt `
```plain
# avahi-browse -arkpt
+;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039hals\039\093\036\032\0352;_qm-labels._tcp;local
+;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039oc\039\093\036;_qm-labels._tcp;local
+;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039hals\039\093\036;_qm-labels._tcp;local
+;eth0;IPv4;QM\032op\032on\032qm-d063b4032f6f;_device-info._tcp;local
+;eth0;IPv4;QM\032oc\032on\032qm-0001c0341100;_device-info._tcp;local
+;eth0;IPv4;QM\032oc\032on\032qm-0001c033cfc3;_device-info._tcp;local
+;eth0;IPv4;QM\032op\032on\032qm-d063b403338f;_device-info._tcp;local
+;eth0;IPv4;qmadm\032\0353;_qm-admin-service._tcp;local
+;eth0;IPv4;qmadm;_qm-admin-service._tcp;local
+;eth0;IPv4;qmadm\032\0352;_qm-admin-service._tcp;local
+;eth0;IPv4;qm-d063b4032f6f\032\091d0\05863\058b4\05803\0582f\0586f\093;_workstation._tcp;local
+;eth0;IPv4;qm-0001c0341100\032\09100\05801\058c0\05834\05811\05800\093;_workstation._tcp;local
+;eth0;IPv4;qm-0001c033cfc3\032\09100\05801\058c0\05833\058cf\058c3\093;_workstation._tcp;local
+;eth0;IPv4;qm-d063b403338f\032\091d0\05863\058b4\05803\05833\0588f\093;_workstation._tcp;local
+;eth0;IPv4;qm-d063b4034ec7\032\091d0\05863\058b4\05803\0584e\058c7\093;_workstation._tcp;local
=;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039hals\039\093\036\032\0352;_qm-labels._tcp;local;qm-d063b4032f6f.local;192.168.88.254;22;
=;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039oc\039\093\036;_qm-labels._tcp;local;qm-0001c033cfc3.local;192.168.88.250;22;
=;eth0;IPv4;\036svc\036\091\039Aliens\039\044\032\039hals\039\093\036;_qm-labels._tcp;local;qm-d063b403338f.local;192.168.88.253;22;
=;eth0;IPv4;QM\032op\032on\032qm-d063b4032f6f;_device-info._tcp;local;qm-d063b4032f6f.local;192.168.88.254;22;
=;eth0;IPv4;QM\032oc\032on\032qm-0001c0341100;_device-info._tcp;local;qm-0001c0341100.local;192.168.88.249;22;
=;eth0;IPv4;QM\032oc\032on\032qm-0001c033cfc3;_device-info._tcp;local;qm-0001c033cfc3.local;192.168.88.250;22;
=;eth0;IPv4;QM\032op\032on\032qm-d063b403338f;_device-info._tcp;local;qm-d063b403338f.local;192.168.88.253;22;
=;eth0;IPv4;qmadm\032\0353;_qm-admin-service._tcp;local;qm-d063b4034ec7.local;192.168.88.252;80;"240430-28342f3$1714478443"
=;eth0;IPv4;qmadm;_qm-admin-service._tcp;local;qm-d063b4032f6f.local;192.168.88.254;80;"240430-28342f3$1714478443"
=;eth0;IPv4;qmadm\032\0352;_qm-admin-service._tcp;local;qm-d063b403338f.local;192.168.88.253;80;"240430-28342f3$1714478443"
=;eth0;IPv4;qm-d063b4032f6f\032\091d0\05863\058b4\05803\0582f\0586f\093;_workstation._tcp;local;qm-d063b4032f6f.local;192.168.88.254;9;
=;eth0;IPv4;qm-0001c0341100\032\09100\05801\058c0\05834\05811\05800\093;_workstation._tcp;local;qm-0001c0341100.local;192.168.88.249;9;
=;eth0;IPv4;qm-0001c033cfc3\032\09100\05801\058c0\05833\058cf\058c3\093;_workstation._tcp;local;qm-0001c033cfc3.local;192.168.88.250;9;
=;eth0;IPv4;qm-d063b403338f\032\091d0\05863\058b4\05803\05833\0588f\093;_workstation._tcp;local;qm-d063b403338f.local;192.168.88.253;9;
=;eth0;IPv4;qm-d063b4034ec7\032\091d0\05863\058b4\05803\0584e\058c7\093;_workstation._tcp;local;qm-d063b4034ec7.local;192.168.88.252;9;
```

## Service qm-sw.service
```plain
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">$svc$['Aliens', 'gateways']$</name>
<service>
<type>_qm-labels._tcp</type>
<port>22</port>
</service>
</service-group>  
```

**Comment by evverx** [comment]
I can't seem to reproduce it. `avahi-browse` shows
```
+;host0;IPv6;\036svc\036\091\039Aliens\039\044\032\039gateways\039\093\036;_qm-labels._tcp;local
+;host0;IPv4;\036svc\036\091\039Aliens\039\044\032\039gateways\039\093\036;_qm-labels._tcp;local
```
as expected.

> 0.7

It was released back in 2017. There have been quite a few fixes since then. Could you try to reproduce it with the master branch?

> a part of the services starts working and is displayed in avahi-browse

Is avahi-browse run on the host where the service is published or on some other host? Could you send `USR1` to `avahi-daemon` to dump its caches if it's on a remote host?

> traffic does not contain qm-sw.service

Could you collect mDNS packets on the host where the service is published?

**Comment by evverx** [comment]
> And restart of avahi helped.

It indicates that the announcements reached that host so the incoming mDNS traffic isn't blocked. Could you make sure that the incoming mDNS traffic on the host where the service is published isn't blocked either? My wild guess would be that `avahi-daemon` wasn't up when the service was published so it missed the announcements and queries didn't reach the host where the service was published.

**Comment by grishy** [comment]
Thanks for the reply!
I am running avahi-browser on the same machine as avahi itself.  
And I also checked the requests in `tcpdump`, and avahi's responses just don't have this service.  
`avahi-browser` response the same on device itself or on other machine in the network. Without `gateways` service.

I will try to reproduce on master branch, but it is also unstable and it is not always possible to reproduce it.

**Comment by evverx** [comment]
> I am running avahi-browser on the same machine as avahi itself.

Got it. It should in theory make it easier to debug it. As far as I can remember there were bugs like that where interfaces were added/withdrawn when avahi was registering services but they should be fixed in the master branch (or the `v0.9-rc1` tag)

**Comment by v4grishy** [comment]
Hi, I checked on the latest version (v0.9-rc1) and could reproduce the behavior.  
The problem, as I see it, is that the service on the device stops advertising one of the services. 
This is fixed with `avahi-daemon` restart.

At the start, it is written in the logs that the service on the file system has been found and started. 
But if you run `avahi-browse` on the same machine, it will not be in the list.

Also from what I suspected. 
This service is called the same on all machines and there is no information in the logs that the name was re-selected.
I don't see any information that the service will select a new name in the avahi logs after launch if it doesn't work.

For context, we have several devices on the network that have the same avahi service. 
We periodically restart all devices at the same time. The restart time is about the same for every device (same HW).

@evverx Do you have any suggestions on how we might approach finding the source of the issue?

**Comment by evverx** [comment]
Could you run avahi with the debug logs enabled (by passing `--debug` to it) and paste the logs? Could you also run `systemctl kill --signal=USR1 avahi-daemon` to dump its "zones" and caches and paste it here too? It should help to figure out what avahi thinks it's advertising.

**Comment by evverx** [comment]
I can see that both `$opd063b4034ec7$['Aliens', 'gateways']$` and `QM op on opd063b4034ec7` were published and all the RR seem to have been present in the cache dump.

Just to make sure as far as I understand one of the services wasn't visible. Did I get it right? Also could you try
```
busctl call org.freedesktop.Avahi / org.freedesktop.Avahi.Server2 ResolveService "iisssiu" -- -1 -1  'QM op on opd063b4034ec7' _device-info._tcp local 0 0
```
(`'QM op on opd063b4034ec7'` and `_device-info._tcp` can be replaced with whatever service isn't visible)

Could you also paste the exact service file and `/etc/avahi/avahi-daemon.conf` so that I could add them on one of my test machines to make it more likely to trigger it there?

**Comment by christianmqm** [comment]
We are still reproducing the issue. It seems to happen more often now; unfortunately not on the systems with debug already enabled. In the meantime, this is the config:
[avahi-daemon.conf.txt](https://github.com/user-attachments/files/16599718/avahi-daemon.conf.txt)

**Comment by christianmqm** [comment]
The service was not visible and I executed your command from above:
```
busctl call org.freedesktop.Avahi / org.freedesktop.Avahi.Server2 ResolveService "iisssiu" -- -1 -1  'QM op on opd063b404f18f' _device-info._tcp local 0 0
Call failed: Timeout reached
```

**Comment by evverx** [comment]
@christianmqm could you also paste `qm-device.service`?

I took the config and rolled it out on a couple of test machines and added a script looking for a `_qm-labels._tcp` services every hour. It should hopefully help to detect that.

The parts where the config differs from the default config are
```sh
allow-interfaces=...
publish-workstation=yes
use-ipv6=no
```
The cache dump doesn't contain `QM op on opd063b404f18f`. I can see a `_device-info._tcp` service but it probably comes from another device:
```
Aug 14 07:55:36 qm-aabbaabb avahi-daemon[572]: QM\032opd\032on\032qm-ddeeddee._device-info._tcp.local        IN        SRV 0 0 22 qm-ddeeddee.local ; ttl=120
Aug 14 07:55:36 qm-aabbaabb avahi-daemon[572]: QM\032opd\032on\032qm-ddeeddee._device-info._tcp.local        IN        TXT  ; ttl=4500
Aug 14 07:55:36 qm-aabbaabb avahi-daemon[572]: _device-info._tcp.local        IN        PTR QM\032opd\032on\032qm-ddeeddee._device-info._tcp.local ; ttl=4500
```

**Comment by christianmqm** [comment]
@evverx Yes, you are right. We have > 10 devices in this network with this service file active:
3 classes of devices where `xxx` is replaced by something.
 
```<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">QM xxx on %h</name>
<service>
<type>_device-info._tcp</type>
<port>22</port>
</service>
</service-group>```

I executed the `busctl` command with the hostname of the machine that was not found at that time. I went back to the cache dump and the service line for that machine is indeed missing. The second service is also missing:

```
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">$%h$['Rome', 'aaa', 'bbb']$</name>
<service>
<type>_qm-labels._tcp</type>
<port>22</port>
</service>
</service-group>
```

What was not missing is the service `_qm-admin-service` but we publish that with a command like `avahi-publish-service -d local qmadm _qm-admin-service._tcp 80 somedata`
I see from the logs that both service files were found on startup and loaded. 24h later (in this case, not saying time is the trigger) they disappeared while the service added with the command above is still available.

I was asked to redact info and unfortunately I did not use the same approach for cache and `busctl`.

**Comment by evverx** [comment]
Got it. I'll add the `_device-info._tcp` service to the test machines too.

If there are any events happening on those devices (like network interfaces going down and up again, time jumps, suspends or anything like that) it would be great if it was possible to extract those events too. They all should be logged in the journal (if it's persistent there).

**Comment by evverx** [comment]
> (in this case, not saying time is the trigger)

I wouldn't rule it out. While I don't think https://github.com/avahi/avahi/pull/96 can help here (because the symptoms are usually different in that case) could you try applying that patch to see if it helps? (That PR should be merged eventually but since it's hugely backward-incompatible it's postponed)

In the meantime I haven't reproduced the issue yet.

**Comment by evverx** [comment]
@christianmqm just to make sure is it reproducible with the master branch (or `v0.9-rc1`) with commits like https://github.com/avahi/avahi/commit/cb15988c4c676410549ef1d04487107cd484b353 included?

**Comment by grishy** [comment]
@evverx we took the tag [v0.9-rc1](https://github.com/avahi/avahi/tree/v0.9-rc1) and it was reproduced on a device with this version...

**Comment by evverx** [comment]
Got it. The test has been running for about 5 days on my test machines and as far as I can see the issue hasn't been reproduced there yet. I'm guessing there are some things happening on those devices that don't happen on my machines.

**Comment by Neustradamus** [comment]
Dear @evverx, @grishy, @v4grishy, @christianmqm,

This ticket exists since more one year.
Any progress with this issue?
It will be fixed in 0.9?
